Attribute VB_Name = "mod_globals"
Public user_type As String
Public user_password As String
Public school_year As String
Public level As String
Public section As String
Public adviser As String
Public status As String
Public user As String
Public stud_name As String
Public id As String
Public log As Integer
